# Generated by Django 4.2.7 on 2023-11-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_laptopmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='laptop_images/', verbose_name='Laptop Image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=100, verbose_name='Order Status'),
        ),
    ]
