# Generated by Django 4.2.7 on 2023-12-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_laptop_images_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('laptops', models.ManyToManyField(to='mainapp.laptop')),
            ],
        ),
    ]
